/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto.Vistas.Panel;


import Proyecto.Poo.Cuentas;
import Proyecto.Vistas.Panel.Controller.PnlFacturasController;

import java.awt.BorderLayout;
import java.awt.Checkbox;
import java.awt.event.ActionEvent;
import java.io.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentListener;
import javax.swing.event.TableModelListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
/**
 *
 * @author rolando
 */
public class StarProg extends javax.swing.JFrame {
    
    InternalDialog internal;
    Cuentas cuentas = new Cuentas();
    public static DefaultTableModel Modelo;
    public static DefaultTableModel FacturaModelo;
    int nuevo=0;
    IternalFacturas internalFact;
    PnlFacturasController pnlFacturasController;
    
    
    TableModel dataModel = new TableModel() {
        @Override
        public int getRowCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getColumnCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public String getColumnName(int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void addTableModelListener(TableModelListener l) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void removeTableModelListener(TableModelListener l) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    };

    /**
     * Creates new form StarProg
     */
    public StarProg() {
        initComponents();
      
        Modelo = new DefaultTableModel();
        FacturaModelo = new DefaultTableModel();
        FacturaModelo.addColumn("Numero De Factura");
        FacturaModelo.addColumn("Nombre Cliemte");
        FacturaModelo.addColumn("Documento");
        LblFecha.setText(LocalDateTime.now().getDayOfWeek().toString()+"/"+LocalDateTime.now().getMonth().toString()+"/"+LocalDateTime.now().getYear());
        
        TblProductos.setModel(Modelo);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnFinalizar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        PnlContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDocumentos = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LblFactura = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnFacturas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProductos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        LblSub = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtDescuento = new javax.swing.JTextField();
        ChDescuento = new java.awt.Checkbox();
        jLabel15 = new javax.swing.JLabel();
        LblValorDesc = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LblIva = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        btnAct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Factura");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Factura de Tienda Manuel S.A");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        BtnFinalizar.setBackground(new java.awt.Color(153, 255, 153));
        BtnFinalizar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnFinalizar.setText("Finalizar Factura");
        BtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnFinalizar);

        BtnLimpiar.setBackground(new java.awt.Color(255, 0, 0));
        BtnLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLimpiar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        PnlContent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Datos del cliente:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N
        jLabel3.setText("Documento:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N
        jLabel4.setText("Direccion:");

        TxtDocumentos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N

        TxtDireccion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N
        jLabel5.setText("Nombres:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N
        jLabel6.setText("Telefono:");

        TxtNombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N

        TxtTelefono.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 10)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        jLabel7.setText("Datos de la factura:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 10)); // NOI18N
        jLabel8.setText("Nº Factura:");

        LblFactura.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        LblFactura.setText("1");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 10)); // NOI18N
        jLabel10.setText("Fecha de la Factura:");

        LblFecha.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        LblFecha.setText("DDdddd/MMmm/YYyy");

        BtnAgregar.setBackground(new java.awt.Color(153, 255, 153));
        BtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(0, 102, 255));
        BtnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnFacturas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnFacturas.setText("FACTURAS");
        BtnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacturasActionPerformed(evt);
            }
        });

        TblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblProductos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TblProductos);
        TblProductos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel12.setText("SubTotal:");

        LblSub.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        LblSub.setText("0");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel14.setText("% Descuento:");

        TxtDescuento.setText("0");

        ChDescuento.setName("Check1"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel15.setText("Valor descontado:");

        LblValorDesc.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        LblValorDesc.setText("0");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel17.setText("IVA 15%:");

        LblIva.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        LblIva.setText("0");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel19.setText("TOTAL FACTURA:");

        LblTotal.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        LblTotal.setText("0");

        btnAct.setText("Actualizar Total");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContentLayout = new javax.swing.GroupLayout(PnlContent);
        PnlContent.setLayout(PnlContentLayout);
        PnlContentLayout.setHorizontalGroup(
            PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(PnlContentLayout.createSequentialGroup()
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(LblSub))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(LblIva))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblTotal))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(LblValorDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAct)
                                .addGap(5, 5, 5))))
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(TxtDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)
                                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlContentLayout.createSequentialGroup()
                                        .addComponent(BtnAgregar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnEliminar))))))
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(44, 44, 44)
                                .addComponent(BtnFacturas))
                            .addGroup(PnlContentLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(LblFactura)
                                .addGap(38, 38, 38)
                                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblFecha)
                                    .addComponent(jLabel10))))))
                .addContainerGap())
        );
        PnlContentLayout.setVerticalGroup(
            PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContentLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BtnFacturas)
                        .addGap(18, 18, 18)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFactura)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlContentLayout.createSequentialGroup()
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(LblSub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ChDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(LblValorDesc)
                        .addComponent(btnAct)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(LblTotal))
                .addContainerGap())
        );

        getContentPane().add(PnlContent, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Limpiar el inicio
    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
      limpiar();
   
    }//GEN-LAST:event_BtnLimpiarActionPerformed
private void limpiar(){
    TxtDocumentos.setText(" ");
        TxtDireccion.setText(" ");
        TxtNombre.setText(" ");
        TxtTelefono.setText(" ");
        TxtDescuento.setText("0");
        ChDescuento.setState(false);
        LblIva.setText("0");
        LblSub.setText("0");
        LblValorDesc.setText("0");
        LblTotal.setText("0");
        
         for( int i = Modelo.getRowCount() - 1; i >= 0; i-- ) {
        Modelo.removeRow(i);
    }
}
private boolean validar(){
    if(TxtDocumentos.getText().isBlank()){
         JOptionPane.showMessageDialog(PnlContent, "Digite la documentacion");
         return false;
    }
     if(TxtDireccion.getText().isBlank()){
         JOptionPane.showMessageDialog(PnlContent, "Digite la direcccion");
         return false;
    }
      if(TxtNombre.getText().isBlank()){
         JOptionPane.showMessageDialog(PnlContent, "Digite el nombre");
         return false;
    }
       if(TxtTelefono.getText().isBlank()){
         JOptionPane.showMessageDialog(PnlContent, "Digite su numero celular");
         return false;
    }
       if(TblProductos.getRowCount()==0){
          JOptionPane.showMessageDialog(PnlContent, "Agregue articulos");
         return false; 
       }
       if(Float.parseFloat(LblTotal.getText())==0){
        JOptionPane.showMessageDialog(PnlContent, "Actualice el total");   
        return false;
       }
    
    return true;
}
    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if(internal == null){
            
              internal = new InternalDialog(this,true);
              internal.setVisible(true);
        }
      internal.setVisible(true);
       
        suma();
        descuento();
        sin();
        iva();
       
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarActionPerformed
       if(validar()== false){
           JOptionPane.showMessageDialog(PnlContent, "La factura NO se guardo con exito!");
           
       }
        else{
              
        JOptionPane.showMessageDialog(PnlContent, "La factura se guardo con exito!");
               
                } 
       //Almacenamieno de datos en el arreglo
 
      
      //
         String[] fila = new String[3];
     fila[0]= LblFactura.getText();
     fila[1] = TxtNombre.getText();
     fila[2] = TxtDocumentos.getText();
     FacturaModelo.addRow(fila);
    File facturaTexto;
    
    facturaTexto = new File("Factura"+LblFactura.getText()+".txt");
        try {
            if(facturaTexto.createNewFile()){
                 JOptionPane.showMessageDialog(PnlContent, "La factura secreo y guardo con exito!");
            }else{
                 JOptionPane.showMessageDialog(PnlContent, "La factura No se guardo!");
            }} catch (IOException ex) {
            Logger.getLogger(StarProg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
           FileWriter w = new FileWriter(facturaTexto);
           BufferedWriter bw = new BufferedWriter(w);
           PrintWriter wr = new PrintWriter(bw);
           
           wr.write("------------FACTURA DE LA TIENDA MANUEL S.A------------");
           wr.append("\nNumero de factura: "+LblFactura.getText());
           wr.append("\nNIT.12234565");
           wr.append("\nUniversidad Nacional de Ingenieria");
           wr.append("\nTelefono: 5555-5555");
           wr.append("\n Fecha: "+LblFecha.getText());
           wr.append("\n\n------------------------------------------------------");
           wr.append("\nDatos del cliente: ");
           wr.append("\n\nNombre: "+ TxtNombre.getText());
           wr.append("\nDireccion: "+ TxtDireccion.getText());
           wr.append("\nDocumentos: "+ TxtTelefono.getText());
           wr.append("\n\nProductos: ");
           wr.append("\n---------------------------------------------------------");
           wr.append("\nProducto"+"\tCantidad"+"\tPrecio");
           wr.append("\n");
         
               
        
           for(int i =0; i<TblProductos.getRowCount();i++){
            
                wr.append((CharSequence) TblProductos.getValueAt(i,0 )+"\t\t"+TblProductos.getValueAt(i,1 )+"\t\t"+TblProductos.getValueAt(i,2 ));
                wr.append("\n");    
           }
           wr.append("\n\n");
            wr.append("Sub Total de su cuenta(Cordobas):\t"+LblSub.getText());
             wr.append("\nDescuento de %"+TxtDescuento.getText()+" :"+ LblValorDesc.getText());
              wr.append("\nIva(15%): "+LblIva.getText());
               wr.append("\nTotal de la cuenta: "+LblTotal.getText()+" Cordobas");
           
           wr.close();
           bw.close();
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(PnlContent, "Hubo un error: "+e);
        }
         limpiar();
             nuevo= Integer.parseInt(LblFactura.getText())+1;
        LblFactura.setText(String.valueOf(nuevo));
         
       
        
    }//GEN-LAST:event_BtnFinalizarActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
         LblTotal.setText(cuentas.Total(Float.parseFloat(LblSub.getText()),Float.parseFloat(LblValorDesc.getText()), Float.parseFloat(LblIva.getText())));
    }//GEN-LAST:event_btnActActionPerformed

    private void BtnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacturasActionPerformed
      if(internalFact == null){
          internalFact = new IternalFacturas(this,true);
          pnlFacturasController = new PnlFacturasController(internalFact);
          internalFact.setVisible(true);
      }
            internalFact.setVisible(true);  
    }//GEN-LAST:event_BtnFacturasActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        
        Modelo.removeRow(TblProductos.getSelectedRow());
        
        
        
    }//GEN-LAST:event_BtnEliminarActionPerformed
private void suma(){
      int suma=0;
      for(int i =0;i<Modelo.getRowCount();i++){
           suma =suma+ (Integer.parseInt(Modelo.getValueAt(i,2).toString())*(Integer.parseInt(Modelo.getValueAt(i,1).toString())));
        }
        LblSub.setText(String.valueOf(suma));
        
        
     /*   if(Integer.parseInt(LblValorDesc.getText())>0){
        LblIva.setText(cuentas.Iva(LblSub.getText(), LblValorDesc.getText()));
        }*/
    
}
private void Total(){
   
    LblTotal.setText(cuentas.Total(Float.parseFloat(LblSub.getText()),Float.parseFloat(LblSub.getText()), Float.parseFloat(LblIva.getText())));
    
}
private void iva(){
     if(Float.parseFloat(LblValorDesc.getText())>0){
        LblIva.setText(cuentas.iva(LblSub.getText(), LblValorDesc.getText()));
}
     
}
private void sin(){
    if(Float.parseFloat(LblSub.getText())>0){
         LblIva.setText(cuentas.IvaSinDescuento(LblSub.getText()));
     }
     
}
private void descuento(){
    float desc =0;
    if(Float.parseFloat(LblSub.getText())>0 && ChDescuento.isEnabled()){
          desc=  Float.parseFloat(cuentas.descuento(LblSub.getText(), TxtDescuento.getText()));
         
        }
    LblValorDesc.setText(String.valueOf(desc));
}
   
    
     private void addComponent(JComponent component) {    
        PnlContent.removeAll();        
        PnlContent.add(component, BorderLayout.CENTER);
        validate();
        repaint();
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StarProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StarProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StarProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StarProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StarProg().setVisible(true);
            }
        });
        
    }

    public JButton getBtnAgregar() {
        return BtnAgregar;
    }

    public void setBtnAgregar(JButton BtnAgregar) {
        this.BtnAgregar = BtnAgregar;
    }

    public JButton getBtnEliminar() {
        return BtnEliminar;
    }

    public void setBtnEliminar(JButton BtnEliminar) {
        this.BtnEliminar = BtnEliminar;
    }

    public JButton getBtnFacturas() {
        return BtnFacturas;
    }

    public void setBtnFacturas(JButton BtnFacturas) {
        this.BtnFacturas = BtnFacturas;
    }

    public JButton getBtnFinalizar() {
        return BtnFinalizar;
    }

    public void setBtnFinalizar(JButton BtnFinalizar) {
        this.BtnFinalizar = BtnFinalizar;
    }

    public JButton getBtnLimpiar() {
        return BtnLimpiar;
    }

    public void setBtnLimpiar(JButton BtnLimpiar) {
        this.BtnLimpiar = BtnLimpiar;
    }

    public Checkbox getChDescuento() {
        return ChDescuento;
    }

    public void setChDescuento(Checkbox ChDescuento) {
        this.ChDescuento = ChDescuento;
    }

    public JLabel getLblFactura() {
        return LblFactura;
    }

    public void setLblFactura(JLabel LblFactura) {
        this.LblFactura = LblFactura;
    }

    public JLabel getLblFecha() {
        return LblFecha;
    }

    public void setLblFecha(JLabel LblFecha) {
        this.LblFecha = LblFecha;
    }

    public JLabel getLblIva() {
        return LblIva;
    }

    public void setLblIva(JLabel LblIva) {
        this.LblIva = LblIva;
    }

    public JLabel getLblSub() {
        return LblSub;
    }

    public void setLblSub(JLabel LblSub) {
        this.LblSub = LblSub;
    }

    public JLabel getLblTotal() {
        return LblTotal;
    }

    public void setLblTotal(JLabel LblTotal) {
        this.LblTotal = LblTotal;
    }

    public JLabel getLblValorDesc() {
        return LblValorDesc;
    }

    public void setLblValorDesc(JLabel LblValorDesc) {
        this.LblValorDesc = LblValorDesc;
    }

    public JTable getTblProductos() {
        return TblProductos;
    }

    public void setTblProductos(JTable TblProductos) {
        this.TblProductos = TblProductos;
    }

    public JTextField getTxtDescuento() {
        return TxtDescuento;
    }

    public void setTxtDescuento(JTextField TxtDescuento) {
        this.TxtDescuento = TxtDescuento;
    }

    public JTextField getTxtDireccion() {
        return TxtDireccion;
    }

    public void setTxtDireccion(JTextField TxtDireccion) {
        this.TxtDireccion = TxtDireccion;
    }

    public JTextField getTxtDocumentos() {
        return TxtDocumentos;
    }

    public void setTxtDocumentos(JTextField TxtDocumentos) {
        this.TxtDocumentos = TxtDocumentos;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JTextField getTxtTelefono() {
        return TxtTelefono;
    }

    public void setTxtTelefono(JTextField TxtTelefono) {
        this.TxtTelefono = TxtTelefono;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return PnlContent;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.PnlContent = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnFacturas;
    private javax.swing.JButton BtnFinalizar;
    private javax.swing.JButton BtnLimpiar;
    private java.awt.Checkbox ChDescuento;
    private javax.swing.JLabel LblFactura;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblIva;
    private javax.swing.JLabel LblSub;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JLabel LblValorDesc;
    private javax.swing.JPanel PnlContent;
    private javax.swing.JTable TblProductos;
    private javax.swing.JTextField TxtDescuento;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDocumentos;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btnAct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
